// Global URLs object accessible to all functions
const URLs = {
    logout: "ajaxhandler/adminLogout.php",
    attendance: "ajaxhandler/approveAttendanceAjax.php",
    history: "ajaxhandler/loadHistoryAjax.php",
    adminDashboard: "ajaxhandler/adminDashboardAjax.php",
    weeklyReports: "ajaxhandler/weeklyReportAjax.php",
    reports: "ajaxhandler/approveReportAjax.php",
    predictions: "ajaxhandler/predictionAjax.php"
};

// Global variable to store current report ID for modal operations
let currentReportId = null;

// Function to handle returning a report
function returnReport(reportId) {
    currentReportId = reportId;
    $('#returnReportModal').show();
    $('#returnReason').val(''); // Clear any previous reason
}

// Function to submit return report
function submitReturnReport() {
    if (!currentReportId) return;

    const reason = $('#returnReason').val().trim();
    if (!reason) {
        alert('Please provide a reason for returning the report.');
        return;
    }

    $.ajax({
        url: URLs.reports,
        type: 'POST',
        data: {
            action: 'returnReport',
            reportId: currentReportId,
            returnReason: reason
        },
        success: function(response) {
            window.isSubmittingReturn = false;
            if (response.status === 'success') {
                // First close the modal
                closeReturnModal();
                // Then show the alert
                alert('Report returned successfully! The student can now edit it.');
                
                // Reset any loading states
                isLoadingReports = false;
                window.isRefreshing = false;
                
                // Clear any existing timeouts
                if (window.refreshTimeout) clearTimeout(window.refreshTimeout);
                if (window.loadingTimeout) clearTimeout(window.loadingTimeout);
                if (window.reportsTimeout) clearTimeout(window.reportsTimeout);
                
                // Then refresh the reports once with current filters
                const studentId = $('#studentFilter').val();
                if (window.currentWeekNumber) {
                    loadWeeklyReports(studentId, window.currentWeekNumber);
                }
            } else {
                closeReturnModal();
                alert('Error: ' + response.message);
            }
        },
        error: function(xhr, status, error) {
            console.error('AJAX Error:', status, error);
            alert('Error connecting to server');
            closeReturnModal();
        }
    });
}

// Function to format time to 12-hour format with AM/PM
function formatTimeToPH(timeString) {
    if (!timeString || timeString === '--:--') return '--:--';
    const timeParts = timeString.split(':');
    const date = new Date();
    date.setHours(parseInt(timeParts[0]), parseInt(timeParts[1]), parseInt(timeParts[2]));
    return date.toLocaleTimeString('en-PH', { timeZone: 'Asia/Manila', hour: '2-digit', minute: '2-digit', hour12: true });
}

$(function () {
    // Analysis Button Click Handler
    $('.analysis-btn').on('click', function() {
        var studentId = $(this).data('student-id');
        if (!studentId) return;
        
        let html = '<p>Loading prediction analysis...</p>';
        if ($('#analysisModal').length === 0) {
            $('body').append('<div id="analysisModal" class="main-dashboard-modal-bg" style="display:none;"><div class="main-dashboard-modal-content"><div class="main-dashboard-modal-header"><h2 class="main-dashboard-modal-title">Prediction Analysis</h2><button class="main-dashboard-modal-close" id="closeAnalysisModal"><i class="fas fa-times"></i></button></div><div class="main-dashboard-modal-body" id="analysisModalContent"></div></div></div>');
        }
        $('#analysisModalContent').html(html);
        $('#analysisModal').fadeIn();

        $.ajax({
            url: URLs.predictions,
            type: 'POST',
            data: {
                action: 'getPreAssessment',
                student_id: studentId
            },
            success: function(response) {
                let html = '';
                const analysis = response;
                if (!analysis || analysis.error || !analysis.placement) {
                    html = `<div class="prediction-card">
                        <div class="no-prediction-message">
                            <i class="fas fa-info-circle"></i>
                            <p>No placement prediction available yet.</p>
                            <p class="prediction-hint">Please note: Predictions are generated by the coordinator in the main dashboard. The prediction will be available here once it has been completed.</p>
                        </div>
                    </div>`;
                } else {
                    function highlightGrades(text) {
                        return text.replace(/([A-Z]{2,} \d{3}: \d{1,3}\.\d+)/g, '<span class="subject-list">$1</span>');
                    }
                    let reasoningLine = '';
                    if (analysis.subjects && analysis.subjects.trim() !== '') {
                        reasoningLine = `<p>Recommended for <span class="highlight">${analysis.placement}</span> due to strong performance in: <span class="subject-list">${analysis.subjects}</span>.</p>`;
                    }
                    html = `<div class="prediction-card">
                        <h3 class="prediction-title">
                            Predicted OJT Placement:
                            <span class="prediction-badge">${analysis.placement}</span>
                        </h3>
                        <div class="prediction-reasoning">
                            <b>Reasoning:</b>
                            ${reasoningLine}
                            <p>
                                ${highlightGrades((analysis.reasoning || '').replace(/\s*\(average: [^)]+\)/g, ''))}
                            </p>
                        </div>
                        <div class="prediction-probability">
                            <b>Probability Explanation:</b>
                            <p>
                                The model is <span class="confidence-high">${analysis.confidence || ''}</span> that <span class="highlight">${analysis.placement}</span> is the best placement for this student. ${analysis.prob_explanation || ''}
                            </p>
                        </div>
                        <div class="probability-bars">
                            ${Object.entries(analysis.probabilities || {}).map(([k, v]) => {
                                let color = '#3867d6';
                                if (k === 'Systems Development') color = '#20bf6b';
                                else if (k === 'Business Operations') color = '#f7b731';
                                else if (k === 'OJT Placement') color = '#eb3b5a';
                                else if (k === 'Research') color = '#3867d6';
                                return `<div class="probability-row"><span>${k}</span><div class="bar" style="width:${v}%;background:${color};"></div><span>${v}%</span></div>`;
                            }).join('')}
                        </div>
                    </div>`;
                }
                $('#analysisModalContent').html(html);
            },
            error: function() {
                $('#analysisModalContent').html('<p>Error loading prediction analysis.</p>');
            }
        });
    });

    // Analysis Modal Close Button Handler
    $(document).on('click', '#closeAnalysisModal', function() {
        $('#analysisModal').fadeOut();
    });

    // Return Report Modal Event Handlers
    $('#closeReturnModal, #cancelReturn').on('click', function() {
        $('#returnReportModal').hide();
        currentReportId = null;
    });

    $('#confirmReturn').on('click', function() {
        submitReturnReport();
    });

    // Close modal when clicking outside
    $('#returnReportModal').on('click', function(e) {
        if (e.target === this) {
            $(this).hide();
            currentReportId = null;
        }
    });

    // Close modal with Escape key
    $(document).on('keyup', function(e) {
        if (e.key === "Escape") {
            $('#returnReportModal').hide();
            currentReportId = null;
        }
    });

    // Close sidebar when clicking outside
    $(document).click(function(e) {
        // Check if sidebar is open and click is outside sidebar and not on the toggle button
        if ($('.sidebar').hasClass('sidebar-open') && 
            !$(e.target).closest('.sidebar').length && 
            !$(e.target).closest('#sidebarToggle').length) {
            $('.sidebar').removeClass('sidebar-open');
            $('.content-area').removeClass('sidebar-open');
        }
    });

    // Analysis Button Click Handler
    $('.analysis-btn').on('click', function() {
        var studentId = $(this).data('student-id');
        if (!studentId) return;
        
        let html = '<p>Loading prediction analysis...</p>';
        if ($('#analysisModal').length === 0) {
            $('body').append('<div id="analysisModal" class="main-dashboard-modal-bg" style="display:none;"><div class="main-dashboard-modal-content"><div class="main-dashboard-modal-header"><h2 class="main-dashboard-modal-title">Prediction Analysis</h2><button class="main-dashboard-modal-close" id="closeAnalysisModal"><i class="fas fa-times"></i></button></div><div class="main-dashboard-modal-body" id="analysisModalContent"></div></div></div>');
        }
        $('#analysisModalContent').html(html);
        $('#analysisModal').fadeIn();

        $.ajax({
            url: 'ajaxhandler/getPreAssessmentAjax.php',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify({ student_id: studentId }),
            success: function(analysis) {
                let html = '';
                if (!analysis || analysis.error || !analysis.placement) {
                    html = `<div class="prediction-card">
                        <div class="no-prediction-message">
                            <i class="fas fa-info-circle"></i>
                            <p>No placement prediction available yet.</p>
                            <p class="prediction-hint">Please note: Predictions are generated when a student uses the Prediction tab in their main dashboard. Once a student accesses that tab, their prediction will be available here.</p>
                        </div>
                    </div>`;
                } else {
                    function highlightGrades(text) {
                        return text.replace(/([A-Z]{2,} \d{3}: \d{1,3}\.\d+)/g, '<span class="subject-list">$1</span>');
                    }
                    let reasoningLine = '';
                    if (analysis.subjects && analysis.subjects.trim() !== '') {
                        reasoningLine = `<p>Recommended for <span class="highlight">${analysis.placement}</span> due to strong performance in: <span class="subject-list">${analysis.subjects}</span>.</p>`;
                    }
                    html = `<div class="prediction-card">
                        <h3 class="prediction-title">
                            Predicted OJT Placement:
                            <span class="prediction-badge">${analysis.placement}</span>
                        </h3>
                        <div class="prediction-reasoning">
                            <b>Reasoning:</b>
                            ${reasoningLine}
                            <p>
                                ${highlightGrades((analysis.reasoning || '').replace(/\s*\(average: [^)]+\)/g, ''))}
                            </p>
                        </div>
                        <div class="prediction-probability">
                            <b>Probability Explanation:</b>
                            <p>
                                The model is <span class="confidence-high">${analysis.confidence || ''}</span> that <span class="highlight">${analysis.placement}</span> is the best placement for this student. ${analysis.prob_explanation || ''}
                            </p>
                        </div>
                        <div class="probability-bars">
                            ${Object.entries(analysis.probabilities || {}).map(([k, v]) => {
                                let color = '#3867d6';
                                if (k === 'Systems Development') color = '#20bf6b';
                                else if (k === 'Business Operations') color = '#f7b731';
                                else if (k === 'OJT Placement') color = '#eb3b5a';
                                else if (k === 'Research') color = '#3867d6';
                                return `<div class="probability-row"><span>${k}</span><div class="bar" style="width:${v}%;background:${color};"></div><span>${v}%</span></div>`;
                            }).join('')}
                        </div>
                    </div>`;
                }
                $('#analysisModalContent').html(html);
            },
            error: function() {
                $('#analysisModalContent').html('<p>Error loading prediction analysis.</p>');
            }
        });
    });

    // Analysis Modal Close Button Handler
    $(document).on('click', '#closeAnalysisModal', function() {
        $('#analysisModal').fadeOut();
    });

    // Close user dropdown when clicking outside
    $(document).click(function(e) {
        const userProfile = $('#userProfile');
        const userDropdown = $('#userDropdown');
        if (!userProfile.is(e.target) && userProfile.has(e.target).length === 0) {
            userDropdown.hide();
        }
    });

    // Tab functionality
    $('.sidebar-item').on('click', function() {
        const tabId = $(this).attr('id');
        
        // Hide all tab contents
        $('.tab-content').hide();
        
        // Show the selected tab content
        if (tabId === 'pendingTab') {
            $('#pendingTabContent').show();
        } else if (tabId === 'dashboardTab') {
            $('#dashboardTabContent').show();
        } else if (tabId === 'historyTab') {
            $('#historyTabContent').show();
            // Auto-load current date when history tab is opened
            const today = new Date().toISOString().split('T')[0];
            const dateInput = document.getElementById('historyDate');
            dateInput.value = today;
            loadHistoryRecords(today);
        } else if (tabId === 'reportsTab') {
            $('#reportsTabContent').show();
               // Automatically load the current week's report when Reports tab is opened
               const today = new Date().toISOString().split('T')[0];
               const dateInput = document.getElementById('dateFilter');
               if (dateInput) {
                   dateInput.value = today;
               }
               let studentId = document.getElementById('studentFilter').value;
               const date = new Date(today);
               const day = date.getDay();
               const diff = date.getDate() - day + (day === 0 ? -6 : 1);
               const weekStart = new Date(date.setDate(diff));
               const weekEnd = new Date(weekStart);
               weekEnd.setDate(weekStart.getDate() + 6);
               const formattedWeekStart = weekStart.toISOString().split('T')[0];
               const formattedWeekEnd = weekEnd.toISOString().split('T')[0];
               document.getElementById('previewWeekNumber').textContent = getWeekNumber(weekStart);
               document.getElementById('previewWeekRange').textContent = `${formattedWeekStart} to ${formattedWeekEnd}`;
               window.currentWeekStart = formattedWeekStart;
               window.currentWeekEnd = formattedWeekEnd;
               if (isNaN(studentId) && studentId !== "") {
                   const options = document.getElementById('studentList').options;
                   for (let i = 0; i < options.length; i++) {
                       if (options[i].value === studentId) {
                           studentId = options[i].getAttribute('data-intern-id');
                           break;
                       }
                   }
               }
               const weekNumber = getWeekNumber(new Date(window.currentWeekStart));
               loadWeeklyReports(studentId, weekNumber);
        } else if (tabId === 'evaluationTab') {
            $('#evaluationTabContent').show();
        } else if (tabId === 'contralTab') {
            $('#contralTabContent').show();
            loadCompaniesMOAData(); // Load MOA data when control tab is opened
        }
        
        // Update active tab
        $('.sidebar-item').removeClass('active');
        $(this).addClass('active');
    });

    function handleAjaxError(xhr, status, error) {
        console.error("AJAX Error:", error);
        console.log("Response text:", xhr.responseText);
        alert(`An error occurred (${status}): ${xhr.statusText}. Please try again.`);
    }

    // Logout functionality
    $(document).on("click", "#btnlogout", function () {
        $.ajax({
            url: URLs.logout,
            type: "POST",
            dataType: "json",
            data: { id: 1 },
            beforeSend: function () {
                $("#btnlogout").prop("disabled", true);
            },
            complete: function () {
                $("#btnlogout").prop("disabled", false);
            },
            success: function (response) {
                document.location.replace("admin.php");
            },
            error: handleAjaxError,
        });
    });

    // Approve attendance functionality
    window.approveAttendance = function (recordId) {
        if (!recordId) {
            alert("Invalid record ID. Please try again.");
            return;
        }

        if (confirm("Are you sure you want to approve this attendance?")) {
            $.ajax({
                url: URLs.attendance,
                type: "POST",
                dataType: "json",
                data: { action: 'approveAttendance', id: recordId },
                beforeSend: function () {
                    console.log(`Sending approval request for record ID: ${recordId}`);
                },
                success: function (response) {
                    if (response.status === 'success') {
                        alert(response.message); // Display success message
                        // Remove the approved record from the table
                        $(`button[onclick="approveAttendance(${recordId})"]`).closest('tr').fadeOut(300, function() {
                            $(this).remove();
                            // Check if there are any remaining records
                            if ($('#pendingTabContent table tbody tr').length === 0) {
                                $('#pendingTabContent table tbody').append('<tr><td colspan="4">No pending attendance records found.</td></tr>');
                            }
                        });
                    } else {
                        alert(`Error: ${response.message}`); // Display error message
                    }
                },
                error: handleAjaxError,
            });
        }
    };

    // Decline attendance functionality
    window.deletePendingAttendance = function (recordId) {
        if (!recordId) {
            alert("Invalid record ID. Please try again.");
            return;
        }

        if (confirm("Are you sure you want to decline this attendance?")) {
            $.ajax({
                url: "ajaxhandler/deletePendingAttendanceAjax.php",
                type: "POST",
                dataType: "json",
                data: { action: 'deletePendingAttendance', id: recordId },
                beforeSend: function () {
                    console.log(`Sending deletion request for record ID: ${recordId}`);
                },
                success: function (response) {
                    if (response.status === 'success') {
                        alert(response.message); // Display success message
                        // Remove the declined record from the table
                        $(`button[onclick="deletePendingAttendance(${recordId})"]`).closest('tr').fadeOut(300, function() {
                            $(this).remove();
                            // Check if there are any remaining records
                            if ($('#pendingTabContent table tbody tr').length === 0) {
                                $('#pendingTabContent table tbody').append('<tr><td colspan="4">No pending attendance records found.</td></tr>');
                            }
                        });
                    } else {
                        alert(`Error: ${response.message}`); // Display error message
                    }
                },
                error: function (xhr, status, error) {
                    console.error("AJAX Error:", error);
                    alert(`An error occurred: ${xhr.statusText}. Please try again.`);
                },
            });
        }
    };

    // Load history records functionality
    document.getElementById('historyDate').addEventListener('change', function() {
        const selectedDate = this.value;
        if (!selectedDate) {
            alert('Please select a date first.');
            return;
        }
        
        loadHistoryRecords(selectedDate);
    });

    // Function to get week range from a date
    function getWeekRange(date) {
        const currentDate = new Date(date);
        const dayOfWeek = currentDate.getDay();
        const diff = currentDate.getDate() - dayOfWeek + (dayOfWeek === 0 ? -6 : 1); // Adjust when day is sunday
        const monday = new Date(currentDate.setDate(diff));
        const sunday = new Date(currentDate.setDate(diff + 6));
        
        return {
            start: monday.toISOString().split('T')[0],
            end: sunday.toISOString().split('T')[0],
            weekNumber: getWeekNumber(monday)
        };
    }

    // Function to get week number
    function getWeekNumber(date) {
        const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
        const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
        const weekNo = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
        return weekNo;
    }

    // Load weekly reports functionality
    document.getElementById('loadReportsBtn').addEventListener('click', function() {
        let studentId = document.getElementById('studentFilter').value;
        const selectedDate = document.getElementById('dateFilter').value;

        if (!selectedDate) {
            alert('Please select a date first.');
            return;
        }

        // Convert selected date to week start and end dates
        const date = new Date(selectedDate);
        const day = date.getDay();
        const diff = date.getDate() - day + (day === 0 ? -6 : 1); // Adjust when day is sunday
        const weekStart = new Date(date.setDate(diff));
        const weekEnd = new Date(weekStart);
        weekEnd.setDate(weekStart.getDate() + 6);

        // Format dates as YYYY-MM-DD to match database format
        const formattedWeekStart = weekStart.toISOString().split('T')[0];
        const formattedWeekEnd = weekEnd.toISOString().split('T')[0];
        
        // Update the preview week range display
        document.getElementById('previewWeekNumber').textContent = getWeekNumber(weekStart);
        document.getElementById('previewWeekRange').textContent = `${formattedWeekStart} to ${formattedWeekEnd}`;

        // Store week dates for the AJAX request
        window.currentWeekStart = formattedWeekStart;
        window.currentWeekEnd = formattedWeekEnd;

        // If studentId is not a number (because user typed a name), try to find matching INTERNS_ID from datalist options
        if (isNaN(studentId) && studentId !== "") {
            const options = document.getElementById('studentList').options;
            for (let i = 0; i < options.length; i++) {
                if (options[i].value === studentId) {
                    studentId = options[i].getAttribute('data-intern-id');
                    break;
                }
            }
        }

        const weekNumber = getWeekNumber(new Date(window.currentWeekStart));
        loadWeeklyReports(studentId, weekNumber);
    });

    // Function to load history records via AJAX
    function loadHistoryRecords(date) {
        $.ajax({
            url: URLs.history,
            type: 'POST',
            dataType: 'json',
            data: { 
                action: 'loadHistory',
                date: date 
            },
            beforeSend: function() {
                // Show loading state
                document.getElementById('historyTableBody').innerHTML = '<tr><td colspan="5" style="text-align: center;">Loading...</td></tr>';
                document.getElementById('historyTable').style.display = 'table';
                document.getElementById('historyNoRecords').style.display = 'none';
            },
            success: function(response) {
                if (response.status === 'success') {
                    // Update summary
                    document.getElementById('selectedDate').textContent = date;
                    document.getElementById('historyPresent').textContent = response.summary.present || 0;
                    document.getElementById('historyOnTime').textContent = response.summary.on_time || 0;
                    document.getElementById('historyLate').textContent = response.summary.late || 0;
                    document.getElementById('historyTotal').textContent = response.summary.total || 0;
                    document.getElementById('historySummary').style.display = 'block';

                    // Populate student lists
                    function populateList(listId, students) {
                        const ul = document.getElementById(listId);
                        ul.innerHTML = '';
                        if (students && students.length > 0) {
                            students.forEach(student => {
                                const li = document.createElement('li');
                                li.textContent = student.SURNAME;
                                ul.appendChild(li);
                            });
                        } else {
                            const li = document.createElement('li');
                            li.textContent = 'No students';
                            ul.appendChild(li);
                        }
                    }

                    // Populate student lists as tables with details
                    function populateTable(tableId, students) {
                        const tbody = document.querySelector(`#${tableId} tbody`);
                        tbody.innerHTML = '';
                        if (students && students.length > 0) {
                            students.forEach(student => {
                                const tr = document.createElement('tr');
                                tr.innerHTML = `
                                    <td>${student.STUDENT_ID}</td>
                                    <td>${student.display_name}</td>
                                    <td>${student.TIMEIN || '--:--'}</td>
                                    <td>${student.TIMEOUT || '--:--'}</td>
                                    <td>${student.status}</td>
                                `;
                                tbody.appendChild(tr);
                            });
                        } else {
                            const tr = document.createElement('tr');
                            tr.innerHTML = `<td colspan="5" style="text-align:center;">No students</td>`;
                            tbody.appendChild(tr);
                        }
                    }

                    // populateTable('historyPresentList', response.presentList);
                    // populateTable('historyOnTimeList', response.onTimeList);
                    // populateTable('historyLateList', response.lateList);
                    // populateTable('historyAbsentList', response.absentList);

                    // Update table
                    if (response.records && response.records.length > 0) {
                        let tableHTML = '';
                        response.records.forEach(function(record) {
                            const statusClass = record.status.toLowerCase().replace(' ', '-');
                            tableHTML += `
                                <tr>
                                    <td>${record.STUDENT_ID}</td>
                                    <td>${record.SURNAME}</td>
                                    <td>${formatTimeToPH(record.TIMEIN)}</td>
                                    <td>${formatTimeToPH(record.TIMEOUT)}</td>
                                    <td class="status-${statusClass}">${record.status}</td>
                                </tr>
                            `;
                        });
                        document.getElementById('historyTableBody').innerHTML = tableHTML;
                        document.getElementById('historyTable').style.display = 'table';
                        document.getElementById('historyNoRecords').style.display = 'none';
                    } else {
                        document.getElementById('historyTable').style.display = 'none';
                        document.getElementById('historyNoRecords').style.display = 'block';
                    }
                } else {
                    alert('Error loading history: ' + response.message);
                }
            },
            error: function(xhr, status, error) {
                console.error('AJAX Error:', error);
                alert('An error occurred while loading history records.');
            }
        });
    }

});

// Profile modal buttons event delegation (since buttons are dynamically loaded)
$(document).on('click', '.btn-edit', function() {
    showEditProfileModal();
});

$(document).on('click', '.btn-change-password', function() {
    showChangePasswordModal();
});

// Function to show Edit Profile modal
function showEditProfileModal() {
    const profileContent = `
        <div class="modal" id="editProfileModal" style="display: flex;">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Edit Profile Picture</h2>
                    <button class="modal-close" id="closeEditProfileModal">&times;</button>
                </div>
                <div class="modal-body">
<form id="editProfileForm" class="edit-profile-picture-form" enctype="multipart/form-data">
                        <div class="profile-picture-section">
                            <div class="current-profile-picture">
                                <div class="avatar-placeholder">
                                    <i class="fas fa-user-shield"></i>
                                </div>
                            </div>
                        <div class="profile-picture-upload file-upload-group">
                            <label for="profilePicture">Upload Profile Picture:</label>
                            <input type="file" id="profilePicture" name="profilePicture" accept="image/*" class="file-input-wrapper">
                            <small>Max file size: 2MB (JPG, PNG, GIF)</small>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn-submit">Save Changes</button>
                        <button type="button" class="btn-cancel" id="closeEditProfileModalCancel">Cancel</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    `;
    // Append modal to body
    $('body').append(profileContent);

    // Close modal event
    $('#closeEditProfileModal, #closeEditProfileModalCancel').on('click', function() {
        $('#editProfileModal').remove();
    });

    // Submit form event
    $('#editProfileForm').on('submit', function(e) {
        e.preventDefault();

        // Validate profile picture file size and type if selected
        const fileInput = $('#profilePicture')[0];
        if (fileInput.files.length === 0) {
            alert('Please select a profile picture to upload.');
            return;
        }

        const file = fileInput.files[0];
        const allowedTypes = ['image/jpeg', 'image/png', 'image/gif'];
        const maxSize = 2 * 1024 * 1024; // 2MB

        if (!allowedTypes.includes(file.type)) {
            alert('Invalid file type. Only JPG, PNG, and GIF are allowed.');
            return;
        }
        if (file.size > maxSize) {
            alert('File size exceeds 2MB limit.');
            return;
        }

        // Prepare FormData for AJAX
        const formData = new FormData();
        formData.append('action', 'updateAdminProfilePicture');
        formData.append('adminId', $('#userName').data('admin-id'));
        formData.append('profilePicture', fileInput.files[0]);

        // Send AJAX request to update profile picture only
        $.ajax({
            url: URLs.adminDashboard,
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            dataType: 'json',
            success: function(response) {
                if (response.status === 'success') {
                    alert('Profile picture updated successfully.');
                    $('#editProfileModal').remove();
                    // Reload profile details in modal
                    loadAdminProfileDetails();
                } else {
                    alert('Error updating profile picture: ' + response.message);
                }
            },
            error: function(xhr, status, error) {
                console.error("AJAX Error:", error);
                alert('An error occurred while updating profile picture.');
            }
        });
    });
}

// Global loading flag to prevent multiple simultaneous calls
let isLoadingReports = false;

// Function to load weekly reports via AJAX
function loadWeeklyReports(studentId, weekNumber) {
    // Allow the request if it's after a return, regardless of loading state
    if (isLoadingReports && !window.isAfterReturn) {
        console.log('Reports are already being loaded, skipping this request...');
        return;
    }
    
    // Clear any existing timeouts
    if (window.reportsTimeout) {
        clearTimeout(window.reportsTimeout);
    }
    if (window.loadingTimeout) {
        clearTimeout(window.loadingTimeout);
    }
    if (window.refreshTimeout) {
        clearTimeout(window.refreshTimeout);
    }
    
    // Set loading flag
    isLoadingReports = true;
    
    // Clear refresh flag if it was set
    window.isRefreshing = false;
    
    // Set a safety timeout to reset all flags after 5 seconds
    window.loadingTimeout = setTimeout(() => {
        isLoadingReports = false;
        window.isRefreshing = false;
        console.log('Loading flags reset by safety timeout');
    }, 5000);

    $.ajax({
        url: URLs.weeklyReports,
        type: 'POST',
        dataType: 'json',
        data: {
            action: 'getWeeklyReports',
            studentId: studentId,
            week: weekNumber,
            weekStart: window.currentWeekStart,
            weekEnd: window.currentWeekEnd,
            adminId: $('#userName').data('admin-id')
        },
        beforeSend: function() {
            // Show loading state
            document.getElementById('reportsLoading').style.display = 'block';
            document.getElementById('reportsList').style.display = 'none';
            document.getElementById('noReports').style.display = 'none';
        },
        success: function(response) {
            document.getElementById('reportsLoading').style.display = 'none';
            // Reset all flags
            isLoadingReports = false;
            window.isRefreshing = false;
            
            // Clear any timeouts
            if (window.loadingTimeout) clearTimeout(window.loadingTimeout);
            if (window.refreshTimeout) clearTimeout(window.refreshTimeout);
            if (window.reportsTimeout) clearTimeout(window.reportsTimeout);
            
            // Only log response if it's from a return report refresh
            if (window.isAfterReturn) {
                console.log("Weekly Reports Response after return:", response);
                window.isAfterReturn = false;
            }
            
            if (response.status === 'success') {
                if (response.reports && response.reports.length > 0) {
                    displayWeeklyReports(response.reports);
                    document.getElementById('reportsList').style.display = 'block';
                    document.getElementById('noReports').style.display = 'none';
                } else {
                    document.getElementById('reportsList').style.display = 'none';
                    document.getElementById('noReports').style.display = 'block';
                }
            } else {
                alert('Error loading reports: ' + response.message);
                document.getElementById('reportsList').style.display = 'none';
                document.getElementById('noReports').style.display = 'block';
            }
        },
        error: function(xhr, status, error) {
            console.error('AJAX Error:', error);
            alert('An error occurred while loading weekly reports.');
            document.getElementById('reportsLoading').style.display = 'none';
            document.getElementById('reportsList').style.display = 'none';
            document.getElementById('noReports').style.display = 'block';
            // Reset loading flag
            isLoadingReports = false;
        }
    });
}

// Function to calculate week number from date
function getWeekNumber(date) {
    const firstDayOfYear = new Date(date.getFullYear(), 0, 1);
    const pastDaysOfYear = (date - firstDayOfYear) / 86400000;
    return Math.ceil((pastDaysOfYear + firstDayOfYear.getDay() + 1) / 7);
}

// Function to display weekly reports
function displayWeeklyReports(reports) {
    const reportsList = document.getElementById('reportsList');
    reportsList.innerHTML = '';

    reports.forEach(report => {
        const reportCard = document.createElement('div');
        reportCard.className = 'report-card admin-report-preview';

        // Calculate week number from week_start date
        let weekNumber = 'undefined';
        if (report.week_start) {
            const weekStartDate = new Date(report.week_start);
            weekNumber = getWeekNumber(weekStartDate);
        }

        // Use the pre-parsed contentPerDay from backend, or parse report_content if not available
        let contentPerDay = {};
        if (report.contentPerDay && typeof report.contentPerDay === 'object') {
            contentPerDay = report.contentPerDay;
        } else if (report.report_content) {
            try {
                // Try to parse as JSON first (new format)
                contentPerDay = JSON.parse(report.report_content);
            } catch (e) {
                // Fallback to old format - put all content in monday
                contentPerDay = {
                    monday: report.report_content,
                    tuesday: '',
                    wednesday: '',
                    thursday: '',
                    friday: ''
                };
            }
        } else {
            contentPerDay = {
                monday: '',
                tuesday: '',
                wednesday: '',
                thursday: '',
                friday: ''
            };
        }

        // Get images per day if available
        const imagesPerDay = report.imagesPerDay || {};
        const legacyImages = report.images || [];

        // Remove fallback that assigns all images to Monday
        // if (!Object.keys(imagesPerDay).length && legacyImages.length > 0) {
        //     imagesPerDay.monday = legacyImages;
        // }

        // Ensure all days have image arrays
        const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'];
        days.forEach(day => {
            if (!imagesPerDay[day]) {
                imagesPerDay[day] = [];
            }
        });

        reportCard.innerHTML = `
            <div class="report-header">
                <h3>${report.student_name} - Week ${weekNumber}</h3>
                <div class="report-meta">
                    <span class="report-period">Period: ${report.week_start} to ${report.week_end}</span>
                    <span class="approval-status ${report.approval_status.toLowerCase()}">${report.approval_status.charAt(0).toUpperCase() + report.approval_status.slice(1)}</span>
                </div>
            </div>

            <div class="report-grid">
                <div class="day-section monday">
                    <h4>Monday</h4>
                    <div class="day-content">
                        <div class="day-images">
                            ${imagesPerDay.monday.map(image => `
                                <img src="${image.url ? image.url : (image.image_path ? image.image_path : '')}" alt="Monday activity" class="activity-image">
                            `).join('')}
                        </div>
                        <div class="day-description">
                            <p>${report.monday_description || 'No description provided for Monday'}</p>
                        </div>
                    </div>
                </div>

                <div class="day-section tuesday">
                    <h4>Tuesday</h4>
                    <div class="day-content">
                        <div class="day-images">
                            ${imagesPerDay.tuesday.map(image => `
                                <img src="${image.url ? image.url : (image.image_path ? image.image_path : '')}" alt="Tuesday activity" class="activity-image">
                            `).join('')}
                        </div>
                        <div class="day-description">
                            <p>${report.tuesday_description || 'No description provided for Tuesday'}</p>
                        </div>
                    </div>
                </div>

                <div class="day-section wednesday">
                    <h4>Wednesday</h4>
                    <div class="day-content">
                        <div class="day-images">
                            ${imagesPerDay.wednesday.map(image => `
                                <img src="${image.url ? image.url : (image.image_path ? image.image_path : '')}" alt="Wednesday activity" class="activity-image">
                            `).join('')}
                        </div>
                        <div class="day-description">
                            <p>${report.wednesday_description || 'No description provided for Wednesday'}</p>
                        </div>
                    </div>
                </div>

                <div class="day-section thursday">
                    <h4>Thursday</h4>
                    <div class="day-content">
                        <div class="day-images">
                            ${imagesPerDay.thursday.map(image => `
                                <img src="${image.url ? image.url : (image.image_path ? image.image_path : '')}" alt="Thursday activity" class="activity-image">
                            `).join('')}
                        </div>
                        <div class="day-description">
                            <p>${report.thursday_description || 'No description provided for Thursday'}</p>
                        </div>
                    </div>
                </div>

                <div class="day-section friday">
                    <h4>Friday</h4>
                    <div class="day-content">
                        <div class="day-images">
                            ${imagesPerDay.friday.map(image => `
                                <img src="${image.url ? image.url : (image.image_path ? image.image_path : '')}" alt="Friday activity" class="activity-image">
                            `).join('')}
                        </div>
                        <div class="day-description">
                            <p>${report.friday_description || 'No description provided for Friday'}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="report-footer">
                <div class="footer-left">
                    ${report.updated_at ? `<span class="updated-date">Last Updated: ${report.updated_at}</span>` : ''}
                </div>
                <div class="footer-right">
                    <button class="action-btn approve-btn" onclick="approveReport(${report.report_id})">Approve</button>
                    <button class="action-btn return-btn" onclick="returnReport(${report.report_id})">Return</button>
                </div>
            </div>
        `;

        reportsList.appendChild(reportCard);
    });
}

// Function to load admin profile details
function loadAdminProfileDetails() {
    // Clear previous content
    $('#profileModalContent').html('');
    
    // Show modal and set loading state
    $('#profileModalContent').html('<div class="loading"><i class="fas fa-spinner fa-spin"></i> Loading profile details...</div>');
    $('#profileModal').css('display', 'flex');
    
    // Fetch profile data from server
    $.ajax({
        url: URLs.adminDashboard,
        type: 'POST',
        dataType: 'json',
        data: {
            action: 'getAdminDetails',
            adminId: $('#userName').data('admin-id')
        },
        success: function(response) {
            if (response.status === 'success') {
                displayAdminProfileDetails(response.data);
            } else {
                alert('Error loading profile details: ' + response.message);
            }
        },
        error: function(xhr, status, error) {
            console.error("AJAX Error:", error);
            alert('An error occurred while loading profile details.');
        }
    });
}

// Function to approve a report
function approveReport(reportId) {
    if (!confirm('Are you sure you want to approve this report?')) {
        return;
    }

    $.ajax({
        url: URLs.reports,
        type: 'POST',
        data: {
            action: 'approveReport',
            reportId: reportId
        },
        success: function(response) {
            if (response.status === 'success') {
                alert('Report approved successfully!');
                // Refresh the reports list
                loadWeeklyReports();
            } else {
                alert('Error: ' + response.message);
            }
        },
        error: function(xhr, status, error) {
            console.error('Error:', error);
            alert('An error occurred while approving the report.');
        }
    });
}

// Modal event handlers
// Document ready handler for admin dashboard
$(document).ready(function() {
    $(document).on('click', '.analysis-btn', function() {
        var studentId = $(this).data('student-id');
        if (!studentId) return;
        
        let html = '<p>Loading prediction analysis...</p>';
        if ($('#analysisModal').length === 0) {
            $('body').append('<div id="analysisModal" class="main-dashboard-modal-bg" style="display:none;"><div class="main-dashboard-modal-content"><div class="main-dashboard-modal-header"><h2 class="main-dashboard-modal-title">Prediction Analysis</h2><button class="main-dashboard-modal-close" id="closeAnalysisModal"><i class="fas fa-times"></i></button></div><div class="main-dashboard-modal-body" id="analysisModalContent"></div></div></div>');
        }
        $('#analysisModalContent').html(html);
        $('#analysisModal').fadeIn();

        $.ajax({
            url: URLs.predictions,
            type: 'POST',
            data: {
                action: 'getPreAssessment',
                student_id: studentId
            },
            success: function(response) {
                let html = '';
                const analysis = response;
                if (!analysis || analysis.error || !analysis.placement) {
                    html = `<div class="prediction-card">
                        <div class="no-prediction-message">
                            <i class="fas fa-info-circle"></i>
                            <p>No placement prediction available yet.</p>
                            <p class="prediction-hint">Please note: Predictions are generated by the coordinator in the main dashboard. The prediction will be available here once it has been completed.</p>
                        </div>
                    </div>`;
                } else {
                    function highlightGrades(text) {
                        return text.replace(/([A-Z]{2,} \d{3}: \d{1,3}\.\d+)/g, '<span class="subject-list">$1</span>');
                    }
                    let reasoningLine = '';
                    if (analysis.subjects && analysis.subjects.trim() !== '') {
                        reasoningLine = `<p>Recommended for <span class="highlight">${analysis.placement}</span> due to strong performance in: <span class="subject-list">${analysis.subjects}</span>.</p>`;
                    }
                    html = `<div class="prediction-card">
                        <h3 class="prediction-title">
                            Predicted OJT Placement:
                            <span class="prediction-badge">${analysis.placement}</span>
                        </h3>
                        <div class="prediction-reasoning">
                            <b>Reasoning:</b>
                            ${reasoningLine}
                            <p>
                                ${highlightGrades((analysis.reasoning || '').replace(/\s*\(average: [^)]+\)/g, ''))}
                            </p>
                        </div>
                        <div class="prediction-probability">
                            <b>Probability Explanation:</b>
                            <p>
                                The model is <span class="confidence-high">${analysis.confidence || ''}</span> that <span class="highlight">${analysis.placement}</span> is the best placement for this student. ${analysis.prob_explanation || ''}
                            </p>
                        </div>
                        <div class="probability-bars">
                            ${Object.entries(analysis.probabilities || {}).map(([k, v]) => {
                                let color = '#3867d6';
                                if (k === 'Systems Development') color = '#20bf6b';
                                else if (k === 'Business Operations') color = '#f7b731';
                                else if (k === 'OJT Placement') color = '#eb3b5a';
                                else if (k === 'Research') color = '#3867d6';
                                return `<div class="probability-row"><span>${k}</span><div class="bar" style="width:${v}%;background:${color};"></div><span>${v}%</span></div>`;
                            }).join('')}
                        </div>
                    </div>`;
                }
                $('#analysisModalContent').html(html);
            },
            error: function() {
                $('#analysisModalContent').html('<p>Error loading prediction analysis.</p>');
            }
        });
    });

    // Analysis Modal Close Button Handler
    $(document).on('click', '#closeAnalysisModal', function() {
        $('#analysisModal').fadeOut();
    });

    // Evaluation tab: load questions and ratings for selected student
    $(document).on('click', '.admin-eval-student', function() {
        $('.admin-eval-student').removeClass('active').css({'background':'#fff','font-weight':'normal'});
        $(this).addClass('active').css({'background':'#e0e7ff','font-weight':'bold'});
        var studentId = $(this).data('student-id');
        $.get('ajaxhandler/getStudentQuestionsAndRatingsAjax.php', {student_id: studentId}, function(data) {
            var result = {};
            try { result = JSON.parse(data); } catch(e) { result = {}; }
            var $main = $('.admin-eval-main');
            $main.empty();
            var hasCategories = false;
            $.each(result, function(category, catData) {
                hasCategories = true;
                var catTitle = 'COMPETENCY ON ' + category.toUpperCase();
                var $catDiv = $('<div class="admin-eval-category" style="margin-bottom:32px;"></div>');
                $catDiv.append('<h3 style="text-transform:uppercase;font-size:18px;margin-bottom:12px;color:#374151;letter-spacing:1px;">'+catTitle+'</h3>');
                    var tableHeader = '<table class="admin-eval-table" style="width:100%;border-collapse:collapse;margin-bottom:12px;"><thead><tr>' +
                        '<th style="border:1px solid #e5e7eb;padding:10px;background:#f3f4f6;font-weight:600;">Question</th>' +
                        '<th class="self-rating-col" style="border:1px solid #e5e7eb;padding:10px;background:#f3f4f6;font-weight:600;width:100px;min-width:100px;max-width:100px;text-align:center;">Self-Rating</th>';
                    for(var i=5;i>=1;i--) {
                        tableHeader += '<th style="border:1px solid #e5e7eb;padding:0;background:#f3f4f6;font-weight:600;width:30px;text-align:center;">'+i+'</th>';
                    }
                    tableHeader += '</tr></thead><tbody></tbody></table>';
                    var $table = $(tableHeader);
                $.each(catData.questions, function(_, q) {
                    var ratingObj = (catData.ratings && catData.ratings[q.id]) ? catData.ratings[q.id] : {};
                    var selfRating = ratingObj.self_rating ? ratingObj.self_rating : '';
                    var $row = $('<tr></tr>').attr('data-question-id', q.question_id);
                    $row.append('<td style="border:1px solid #e5e7eb;padding:10px;">'+q.question_text+'</td>');
                    $row.append('<td class="self-rating-col" style="border:1px solid #e5e7eb;padding:10px;width:100px;min-width:100px;max-width:100px;text-align:center;">'+selfRating+'</td>');
                            for(var i=5;i>=1;i--) {
                                var radioName = 'admin_rating_'+category+'_'+q.id;
                            var supervisorRating = ratingObj.supervisor_rating ? ratingObj.supervisor_rating : '';
                            var checked = (supervisorRating == i) ? 'checked' : '';
                                $row.append('<td style="border:1px solid #e5e7eb;padding:0;width:30px;text-align:center;vertical-align:middle;">'+
                                    '<input type="radio" name="'+radioName+'" value="'+i+'" style="margin:0;" '+checked+'>'+
                                '</td>');
                            }
                        $table.find('tbody').append($row);
                });
                $catDiv.append($table);
                $main.append($catDiv);
            });
                // Add comments/recommendations table after all competency tables
                if(hasCategories) {
                    // Find the first non-empty comment for this student
                    var commentsText = '';
                    outer: for (var category in result) {
                        var catData = result[category];
                        for (var i = 0; i < catData.questions.length; i++) {
                            var q = catData.questions[i];
                            var ratingObj = (catData.ratings && catData.ratings[q.id]) ? catData.ratings[q.id] : {};
                            if (ratingObj.comment && ratingObj.comment.trim() !== '') {
                                commentsText = ratingObj.comment;
                                break outer;
                            }
                        }
                    }
                    var commentsTable = '<div class="admin-eval-comments-section" style="margin-top:32px;">'+
                        '<h3 style="font-size:17px;color:#2563eb;margin-bottom:12px;">Comments / Recommendations</h3>'+
                        '<table class="admin-eval-comments-table" style="width:100%;border-collapse:collapse;">'+
                            '<thead><tr>'+
                                '<th style="border:1px solid #e5e7eb;padding:10px;background:#f3f4f6;font-weight:600;width:200px;">Comment/Recommendation</th>'+
                                '<th style="border:1px solid #e5e7eb;padding:10px;background:#f3f4f6;font-weight:600;width:120px;">Date</th>'+
                            '</tr></thead>'+
                            '<tbody>'+
                                '<tr>'+
                                    '<td colspan="2" style="border:1px solid #e5e7eb;padding:10px;text-align:left;">'+
                                        '<textarea class="admin-eval-comment-input" name="comment" placeholder="Add a comment or recommendation..." style="width:100%;padding:8px 12px;border-radius:4px;border:1px solid #ccc;font-size:15px;min-height:60px;">'+commentsText+'</textarea>'+
                                    '</td>'+
                                '</tr>'+
                            '</tbody>'+
                        '</table>'+
                    '</div>';
                    $main.append(commentsTable);
                }
            if(hasCategories) {
                $main.append('<button class="admin-eval-save-btn" style="background:#2563eb;color:#fff;border:none;border-radius:4px;padding:12px 32px;font-size:16px;font-weight:600;cursor:pointer;box-shadow:0 1px 4px rgba(37,99,235,0.08);transition:background 0.2s;">Save Evaluation</button>');
            } else {
                $main.append('<div style="padding:32px;text-align:center;color:#374151;">No questions or ratings found for this student.</div>');
            }
        });
    });
        // Save Evaluation button handler
        $(document).on('click', '.admin-eval-save-btn', function() {
            var $main = $('.admin-eval-main');
            var studentId = $('.admin-eval-student.active').data('student-id');
            if(!studentId) {
                alert('No student selected.');
                return;
            }
            // Collect ratings per category/question
            var ratings = [];
            $main.find('.admin-eval-category').each(function() {
                var category = $(this).find('h3').text().replace('COMPETENCY ON ','').trim();
                $(this).find('table.admin-eval-table tbody tr').each(function(idx) {
                    var questionText = $(this).find('td').eq(0).text();
                    var selfRating = $(this).find('td.self-rating-col').text();
                    var adminRating = $(this).find('input[type=radio]:checked').val() || null;
                    var questionId = $(this).attr('data-question-id');
                    ratings.push({
                        category: category,
                        question_id: questionId,
                        question_text: questionText,
                        self_rating: selfRating,
                        admin_rating: adminRating
                    });
                });
            });

            // Analysis Button Click Handler
            $('.analysis-btn').on('click', function() {
                var studentId = $(this).data('student-id');
                if (!studentId) return;
                
                let html = '<p>Loading prediction analysis...</p>';
                if ($('#analysisModal').length === 0) {
                    $('body').append('<div id="analysisModal" class="main-dashboard-modal-bg" style="display:none;"><div class="main-dashboard-modal-content"><div class="main-dashboard-modal-header"><h2 class="main-dashboard-modal-title">Prediction Analysis</h2><button class="main-dashboard-modal-close" id="closeAnalysisModal"><i class="fas fa-times"></i></button></div><div class="main-dashboard-modal-body" id="analysisModalContent"></div></div></div>');
                }
                $('#analysisModalContent').html(html);
                $('#analysisModal').fadeIn();

                $.ajax({
                    url: 'ajaxhandler/predictionAjax.php',
                    type: 'POST',
                    data: {
                        action: 'getPreAssessment',
                        student_id: studentId
                    },
                    success: function(analysis) {
                        let html = '';
                        if (!analysis || analysis.error || !analysis.placement) {
                            html = `<div class="prediction-card">
                                <div class="no-prediction-message">
                                    <i class="fas fa-info-circle"></i>
                                    <p>No placement prediction available yet.</p>
                                    <p class="prediction-hint">Please note: Predictions are generated when a student uses the Prediction tab in their main dashboard. Once a student accesses that tab, their prediction will be available here.</p>
                                </div>
                            </div>`;
                        } else {
                            html = `<div class="prediction-card">
                                <h3 class="prediction-title">
                                    Predicted OJT Placement:
                                    <span class="prediction-badge">${analysis.placement}</span>
                                </h3>
                                <div class="prediction-reasoning">
                                    <b>Reasoning:</b>
                                    <p>${analysis.reasoning}</p>
                                </div>
                                <div class="prediction-probability">
                                    <b>Probability Explanation:</b>
                                    <p>
                                        The model is <span class="confidence-high">${analysis.confidence || ''}</span> that <span class="highlight">${analysis.placement}</span> is the best placement for this student. ${analysis.prob_explanation || ''}
                                    </p>
                                </div>
                                <div class="probability-bars">
                                    ${Object.entries(analysis.probabilities || {}).map(([k, v]) => {
                                        let color = '#3867d6';
                                        if (k === 'Systems Development') color = '#20bf6b';
                                        else if (k === 'Business Operations') color = '#f7b731';
                                        else if (k === 'OJT Placement') color = '#eb3b5a';
                                        else if (k === 'Research') color = '#3867d6';
                                        return `<div class="probability-row"><span>${k}</span><div class="bar" style="width:${v}%;background:${color};"></div><span>${v}%</span></div>`;
                                    }).join('')}
                                </div>
                                <div class="prediction-probability">
                                    <b>Probability Explanation:</b>
                                    <p>${analysis.prob_explanation}</p>
                                </div>
                            </div>`;
                        }
                        $('#analysisModalContent').html(html);
                    },
                    error: function() {
                        $('#analysisModalContent').html('<p>Error loading prediction analysis.</p>');
                    }
                });
            });

            // Analysis Modal Close Button Handler
            $(document).on('click', '#closeAnalysisModal', function() {
                $('#analysisModal').fadeOut();
            });

            console.log('DEBUG: Ratings to send:', ratings);
            // Get comment
            var comment = $main.find('.admin-eval-comment-input').val();
            // Send AJAX to save
            $.ajax({
                url: 'ajaxhandler/saveAdminEvaluationAjax.php',
                type: 'POST',
                dataType: 'json',
                data: {
                    student_id: studentId,
                    ratings: JSON.stringify(ratings),
                    comment: comment
                },
                success: function(resp) {
                    if(resp.status==='success') {
                        alert('Evaluation saved successfully!');
                    } else {
                        alert('Error saving evaluation: '+resp.message);
                    }
                },
                error: function(xhr, status, error) {
                    alert('AJAX error: '+error);
                }
            });
        });
    // Evaluation tab student search filter
    $(document).on('input', '.admin-eval-search', function() {
        var searchTerm = $(this).val().toLowerCase();
        $('.admin-eval-student-list .admin-eval-student').each(function() {
            var name = $(this).text().toLowerCase();
            if (name.indexOf(searchTerm) !== -1 || searchTerm === '') {
                $(this).show();
            } else {
                $(this).hide();
            }
        });
    });
    const closeBtn = document.getElementById('closeReturnModal');
    const cancelBtn = document.getElementById('cancelReturn');
    const confirmBtn = document.getElementById('confirmReturn');

    if (closeBtn) closeBtn.onclick = closeReturnModal;
    if (cancelBtn) cancelBtn.onclick = closeReturnModal;
    if (confirmBtn) confirmBtn.onclick = submitReturnReport;
});

function closeReturnModal() {
    const modal = document.getElementById('returnReportModal');
    if (modal) {
        modal.style.display = 'none';
        $('#returnReason').val('');
        currentReportId = null;
    }
}

function submitReturnReport() {
    const reason = document.getElementById('returnReason').value.trim();
    if (!reason) {
        alert('Please provide a return reason');
        return;
    }

    if (!currentReportId) {
        alert('No report selected');
        return;
    }

    // Prevent duplicate submissions
    if (window.isSubmittingReturn) {
        return;
    }
    window.isSubmittingReturn = true;

    $.ajax({
        url: URLs.reports,
        type: 'POST',
        data: {
            action: 'returnReport',
            reportId: currentReportId,
            returnReason: reason
        },
            success: function(response) {
                let html = '';
                const analysis = response;
                if (!analysis || analysis.error || !analysis.placement) {
                    html = `<div class="prediction-card">
                        <div class="no-prediction-message">
                            <i class="fas fa-info-circle"></i>
                            <p>No placement prediction available yet.</p>
                            <p class="prediction-hint">Please note: Predictions are generated by the coordinator in the main dashboard. The prediction will be available here once it has been completed.</p>
                        </div>
                    </div>`;
                } else {
                    function highlightGrades(text) {
                        return text.replace(/([A-Z]{2,} \d{3}: \d{1,3}\.\d+)/g, '<span class="subject-list">$1</span>');
                    }
                    let reasoningLine = '';
                    if (analysis.subjects && analysis.subjects.trim() !== '') {
                        reasoningLine = `<p>Recommended for <span class="highlight">${analysis.placement}</span> due to strong performance in: <span class="subject-list">${analysis.subjects}</span>.</p>`;
                    }
                    html = `<div class="prediction-card">
                        <h3 class="prediction-title">
                            Predicted OJT Placement:
                            <span class="prediction-badge">${analysis.placement}</span>
                        </h3>
                        <div class="prediction-reasoning">
                            <b>Reasoning:</b>
                            ${reasoningLine}
                            <p>
                                ${highlightGrades((analysis.reasoning || '').replace(/\s*\(average: [^)]+\)/g, ''))}
                            </p>
                        </div>
                        <div class="prediction-probability">
                            <b>Probability Explanation:</b>
                            <p>
                                The model is <span class="confidence-high">${analysis.confidence || ''}</span> that <span class="highlight">${analysis.placement}</span> is the best placement for this student. ${analysis.prob_explanation || ''}
                            </p>
                        </div>
                        <div class="probability-bars">
                            ${Object.entries(analysis.probabilities || {}).map(([k, v]) => {
                                let color = '#3867d6';
                                if (k === 'Systems Development') color = '#20bf6b';
                                else if (k === 'Business Operations') color = '#f7b731';
                                else if (k === 'OJT Placement') color = '#eb3b5a';
                                else if (k === 'Research') color = '#3867d6';
                                return `<div class="probability-row"><span>${k}</span><div class="bar" style="width:${v}%;background:${color};"></div><span>${v}%</span></div>`;
                            }).join('')}
                        </div>
                    </div>`;
                }
                $('#analysisModalContent').html(html);
            },
            error: function() {
                $('#analysisModalContent').html('<p>Error loading prediction analysis.</p>');
            }
        });


    $(document).on('click', '#closeAnalysisModal', function() {
        $('#analysisModal').fadeOut();
    });

    $.ajax({
        url: URLs.reports,
        type: 'POST',
        data: {
            action: 'returnReport',
            reportId: currentReportId,
            returnReason: reason
        },
        success: function(response) {
            window.isSubmittingReturn = false;
            if (response.status === 'success') {
                // First close the modal
                closeReturnModal();
                // Then show the alert
                alert('Report returned successfully! The student can now edit it.');
                
                // Reset any loading states
                isLoadingReports = false;
                window.isRefreshing = false;
                
                // Clear any existing timeouts
                if (window.refreshTimeout) clearTimeout(window.refreshTimeout);
                if (window.loadingTimeout) clearTimeout(window.loadingTimeout);
                if (window.reportsTimeout) clearTimeout(window.reportsTimeout);
                
                // Set flag to indicate this refresh is after a return
                window.isAfterReturn = true;
                
                // Then refresh the reports with current filters
                const studentId = $('#studentFilter').val();
                // Get the current week number from the preview
                const weekNumber = parseInt($('#previewWeekNumber').text());
                if (weekNumber) {
                    loadWeeklyReports(studentId, weekNumber);
                }
            } else {
                closeReturnModal();
                alert('Error: ' + response.message);
            }
        },
        error: function(xhr, status, error) {
            window.isSubmittingReturn = false;
            console.error('Error:', error);
            alert('An error occurred while returning the report.');
            closeReturnModal();
        }
    });
}

// Function to display admin profile details
function displayAdminProfileDetails(data) {
    // Check if profile picture exists
    const profilePicture = data.PROFILE ? `uploads/${data.PROFILE}` : null;
    
    const html = `
        <div class="profile-card">
            <div class="profile-header">
                <div class="profile-avatar">
                    ${profilePicture ? 
                        `<img src="${profilePicture}" alt="Profile Picture" class="profile-image">` :
                        `<div class="avatar-placeholder">
                            <i class="fas fa-user-shield"></i>
                         </div>`
                    }
                </div>
                <h2>${data.NAME}</h2>
                <p class="profile-subtitle">HTE Manager</p>
            </div>
            
            <div class="profile-details">
                <div class="detail-row">
                    <span class="detail-label">Manager ID:</span>
                    <span class="detail-value">${data.COORDINATOR_ID}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Full Name:</span>
                    <span class="detail-value">${data.NAME}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Email:</span>
                    <span class="detail-value">${data.EMAIL}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Contact Number:</span>
                    <span class="detail-value">${data.CONTACT_NUMBER}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Department:</span>
                    <span class="detail-value">${data.DEPARTMENT}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">HTE:</span>
                    <span class="detail-value">${data.HTE_NAME}</span>
                </div>
            </div>
            
            <div class="profile-actions">
                <button type="button" class="btn-edit">Edit Profile</button>
                <button type="button" class="btn-change-password">Change Password</button>
            </div>
        </div>
    `;
    
    $('#profileModalContent').html(html);
}

// Function to show Change Password modal
function showChangePasswordModal() {
    const passwordContent = `
        <div class="modal" id="changePasswordModal" style="display: flex;">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Change Password</h2>
                    <button class="modal-close" id="closeChangePasswordModal">&times;</button>
                </div>
                <div class="modal-body">
<form id="changePasswordForm" class="change-password-form">
    <h3>Update Your Password</h3>
    <div class="form-group">
        <label for="currentPassword">Current Password:</label>
        <input type="password" id="currentPassword" name="currentPassword" required>
    </div>
    <div class="form-group">
        <label for="newPassword">New Password:</label>
        <input type="password" id="newPassword" name="newPassword" required>
    </div>
    <div class="form-group">
        <label for="confirmPassword">Confirm New Password:</label>
        <input type="password" id="confirmPassword" name="confirmPassword" required>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn-submit">Change Password</button>
        <button type="button" class="btn-cancel" id="closeChangePasswordModalCancel">Cancel</button>
    </div>
</form>
                </div>
            </div>
        </div>
    `;
    // Append modal to body
    $('body').append(passwordContent);

    // Close modal event
    $('#closeChangePasswordModal, #closeChangePasswordModalCancel').on('click', function() {
        $('#changePasswordModal').remove();
    });

    // Submit form event
    $('#changePasswordForm').on('submit', function(e) {
        e.preventDefault();
        const currentPassword = $('#currentPassword').val().trim();
        const newPassword = $('#newPassword').val().trim();
        const confirmPassword = $('#confirmPassword').val().trim();

        if (!currentPassword || !newPassword || !confirmPassword) {
            alert('Please fill in all fields.');
            return;
        }

        if (newPassword !== confirmPassword) {
            alert('New password and confirmation do not match.');
            return;
        }

        // Send AJAX request to update password
        $.ajax({
            url: URLs.adminDashboard,
            type: 'POST',
            dataType: 'json',
            data: {
                action: 'updatePassword',
                adminId: $('#userName').data('admin-id'),
                currentPassword: currentPassword,
                newPassword: newPassword,
                confirmPassword: confirmPassword
            },
            success: function(response) {
                if (response.status === 'success') {
                    alert('Password changed successfully.');
                    $('#changePasswordModal').remove();
                } else {
                    alert('Error changing password: ' + response.message);
                }
            },
            error: function(xhr, status, error) {
                console.error("AJAX Error:", error);
                alert('An error occurred while changing password.');
            }
        });
    });
}

// MOA Status Calculation Utility (reused from mainDashboard.js)
function calculateMOAStatus(startDate, endDate) {
    if (!startDate || !endDate) {
        return { status: 'No MOA', color: '#6c757d' };
    }
    
    const today = new Date();
    const start = new Date(startDate);
    const end = new Date(endDate);
    
    // Remove time part for accurate comparison
    today.setHours(0, 0, 0, 0);
    start.setHours(0, 0, 0, 0);
    end.setHours(0, 0, 0, 0);
    
    if (today < start) {
        return { status: 'Future', color: '#17a2b8' };
    } else if (today >= start && today <= end) {
        // Check if expiring within 30 days
        const daysUntilExpiry = Math.ceil((end - today) / (1000 * 60 * 60 * 24));
        if (daysUntilExpiry <= 30) {
            return { status: 'Expiring Soon', color: '#ffc107' };
        }
        return { status: 'Active', color: '#28a745' };
    } else {
        return { status: 'Expired', color: '#dc3545' };
    }
}

// Load admin's assigned company MOA data for admin control panel
function loadCompaniesMOAData() {
    // Get admin ID from the userName data attribute
    const adminId = $('#userName').data('admin-id');
    
    if (!adminId) {
        $('#companiesMOATableBody').html(`
            <tr>
                <td colspan="6" style="padding: 40px; text-align: center; color: #dc3545;">
                    <div style="display: flex; flex-direction: column; align-items: center; gap: 10px;">
                        <i class="fas fa-exclamation-triangle" style="font-size: 24px;"></i>
                        <p>Admin ID not found. Please log in again.</p>
                    </div>
                </td>
            </tr>
        `);
        return;
    }
    
    $.ajax({
        url: 'ajaxhandler/attendanceAJAX.php',
        type: 'POST',
        dataType: 'json',
        data: { action: 'getAllHTEList', adminId: adminId }, // Get admin's assigned HTE
        beforeSend: function() {
            $('#companiesMOATableBody').html(`
                <tr>
                    <td colspan="6" style="padding: 40px; text-align: center; color: #666;">
                        <div style="display: flex; flex-direction: column; align-items: center; gap: 10px;">
                            <i class="fas fa-spinner fa-spin" style="font-size: 24px; color: #007bff;"></i>
                            <p>Loading companies...</p>
                        </div>
                    </td>
                </tr>
            `);
        },
        success: function(response) {
            if (response.success && response.htes && Array.isArray(response.htes)) {
                if (response.htes.length > 0) {
                    renderCompaniesMOATable(response.htes);
                    updateMOAStatistics(response.htes);
                } else {
                    $('#companiesMOATableBody').html(`
                        <tr>
                            <td colspan="6" style="padding: 40px; text-align: center; color: #666;">
                                <div style="display: flex; flex-direction: column; align-items: center; gap: 10px;">
                                    <i class="fas fa-building" style="font-size: 24px; color: #6c757d;"></i>
                                    <p>No company assigned to your account</p>
                                </div>
                            </td>
                        </tr>
                    `);
                }
            } else {
                $('#companiesMOATableBody').html(`
                    <tr>
                        <td colspan="6" style="padding: 40px; text-align: center; color: #dc3545;">
                            <div style="display: flex; flex-direction: column; align-items: center; gap: 10px;">
                                <i class="fas fa-exclamation-triangle" style="font-size: 24px;"></i>
                                <p>Error loading company: ${response.message || 'Unknown error'}</p>
                            </div>
                        </td>
                    </tr>
                `);
            }
        },
        error: function(xhr, status, error) {
            console.error('Error loading companies:', error);
            $('#companiesMOATableBody').html(`
                <tr>
                    <td colspan="6" style="padding: 40px; text-align: center; color: #dc3545;">
                        <div style="display: flex; flex-direction: column; align-items: center; gap: 10px;">
                            <i class="fas fa-exclamation-triangle" style="font-size: 24px;"></i>
                            <p>Error loading your assigned company. Please try again.</p>
                        </div>
                    </td>
                </tr>
            `);
        }
    });
}

// Render companies MOA table
function renderCompaniesMOATable(companies) {
    let html = '';
    
    companies.forEach(function(company) {
        const moaStatus = calculateMOAStatus(company.MOA_START_DATE, company.MOA_END_DATE);
        
        // Format dates
        let moaDatesText = '-';
        if (company.MOA_START_DATE && company.MOA_END_DATE) {
            const startDate = new Date(company.MOA_START_DATE).toLocaleDateString();
            const endDate = new Date(company.MOA_END_DATE).toLocaleDateString();
            moaDatesText = `${startDate} - ${endDate}`;
        }
        
        // MOA view button
        let moaViewBtn = '';
        if (company.MOA_FILE_URL) {
            moaViewBtn = `<button class="view-moa-btn-admin" data-moa="${company.MOA_FILE_URL}" 
                style="padding: 4px 8px; background: #17a2b8; color: white; border: none; border-radius: 3px; cursor: pointer; margin-left: 5px;">
                <i class="fas fa-file-pdf"></i> View MOA
            </button>`;
        }
        
        html += `
            <tr data-company-id="${company.HTE_ID}" style="border-bottom: 1px solid #eee;">
                <td style="padding: 12px; color: #333;">${company.NAME || '-'}</td>
                <td style="padding: 12px; color: #666;">${company.INDUSTRY || '-'}</td>
                <td style="padding: 12px; color: #666;">${company.CONTACT_PERSON || '-'}</td>
                <td style="padding: 12px;">
                    <span style="padding: 4px 8px; border-radius: 12px; font-size: 12px; font-weight: 600; 
                        background-color: ${moaStatus.color}20; color: ${moaStatus.color};">
                        ${moaStatus.status}
                    </span>
                </td>
                <td style="padding: 12px; color: #666; font-size: 14px;">${moaDatesText}</td>
                <td style="padding: 12px;">
                    <div style="display: flex; gap: 5px; align-items: center;">
                        ${moaViewBtn}
                    </div>
                </td>
            </tr>
        `;
    });
    
    $('#companiesMOATableBody').html(html);
}

// Note: Company filter not needed for admin - they only see their assigned company

// Update MOA statistics
function updateMOAStatistics(companies) {
    let activeMOAs = 0;
    let expiringSoonMOAs = 0;
    let expiredMOAs = 0;
    let noMOACompanies = 0;
    
    companies.forEach(function(company) {
        const moaStatus = calculateMOAStatus(company.MOA_START_DATE, company.MOA_END_DATE);
        
        switch(moaStatus.status) {
            case 'Active':
                activeMOAs++;
                break;
            case 'Expiring Soon':
                expiringSoonMOAs++;
                break;
            case 'Expired':
                expiredMOAs++;
                break;
            case 'No MOA':
                noMOACompanies++;
                break;
        }
    });
    
    $('#activeMOAs').text(activeMOAs);
    $('#expiringSoonMOAs').text(expiringSoonMOAs);
    $('#expiredMOAs').text(expiredMOAs);
    $('#noMOACompanies').text(noMOACompanies);
}

// Event handlers for admin control panel
$(document).ready(function() {
    // Refresh companies button
    $(document).on('click', '#refreshCompaniesBtn', function() {
        loadCompaniesMOAData();
    });
    
    // No company filter needed - admin only sees their assigned company
    
    // MOA view button (read-only for admin)
    $(document).on('click', '.view-moa-btn-admin', function() {
        const moaPath = $(this).data('moa');
        if (moaPath) {
            window.open(moaPath, '_blank');
        }
    });
    
    // Company details view removed - unnecessary for admin interface
});
